services:
  dev:
    image: mcr.microsoft.com/devcontainers/base:ubuntu-24.04
    volumes:
      - ..:/workspaces/bdd-selenium-java-lab:cached
    command: sleep infinity
    depends_on:
      - selenium
    networks:
      - bddnet
    environment:
      - JAVA_TOOL_OPTIONS=-Djava.net.preferIPv4Stack=true -Djava.net.preferIPv6Addresses=false

  selenium:
    image: selenium/standalone-chrome
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "7900:7900"
    environment:
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_START_XVFB=true
    networks:
      - bddnet

networks:
  bddnet:
    driver: bridge
    enable_ipv6: false
